//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Agenda.h
//  @ Date : 4/18/2016
//  @ Author : 
//
//


#if !defined(_AGENDA_H)
#define _AGENDA_H
#include "Contact.h"

class Agenda {
private:
	vector <Contact> ContactList;
public:
	void SearchContactByName();
	void FriendList();
	void DeleteContactByName();
	void AddContact();
};

#endif  //_AGENDA_H
