//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Agenda.cpp
//  @ Date : 4/18/2016
//  @ Author : 
//
//


#include "Agenda.h"
template <class T>
T Agenda::SearchContactByName(string name) {
	for (auto it = ContactList.begin;it != ContactList.end;it++)
		if (ContactList[*it].nume == nume)
			return ContactList[*it];
}

void Agenda::FriendList() {

}

void Agenda::DeleteContactByName() {
}

void Agenda::AddContact() {
}

