//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Coleg.h
//  @ Date : 4/18/2016
//  @ Author : 
//
//


#if !defined(_COLEG_H)
#define _COLEG_H

#include "Contact.h"

class Coleg : public Contact {
public:
	int Numar;
	string Firma,Adresa;
};

#endif  //_COLEG_H
