//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Contact.h
//  @ Date : 4/18/2016
//  @ Author : 
//
//


#if !defined(_CONTACT_H)
#define _CONTACT_H
#include "Coleg.h"
#include "Cunoscut.h"
#include "Prieten.h"

class Contact : public Coleg, public Cunoscut,public Prieten {
public:
	string Nume;
};

#endif  //_CONTACT_H
