//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Cunoscut.h
//  @ Date : 4/18/2016
//  @ Author : 
//
//


#if !defined(_CUNOSCUT_H)
#define _CUNOSCUT_H

#include "Contact.h"

class Cunoscut : public Contact {
public:
	int Numar;
};

#endif  //_CUNOSCUT_H
