//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Prieten.h
//  @ Date : 4/18/2016
//  @ Author : 
//
//


#if !defined(_PRIETEN_H)
#define _PRIETEN_H

#include "Contact.h"

class Prieten : public Contact{
public:
	int Data_Nastere;
	int Numar;
	string Adresa;
};

#endif  //_PRIETEN_H
