#include "Computer.h"




void Computer::Remove(Observer *o)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-43-38--3b86ddc6:154b7f262c7:-8000:0000000000000894 begin
{
	/*for(auto it=myObserver.begin();it!=myObserver.end();it++)
		if(*it==*o)
		*/
}
// section -64--88-43-38--3b86ddc6:154b7f262c7:-8000:0000000000000894 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Computer::Add(Observer *o)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-43-38--3b86ddc6:154b7f262c7:-8000:0000000000000896 begin
{
	myObserver.push_back(*o);
}
// section -64--88-43-38--3b86ddc6:154b7f262c7:-8000:0000000000000896 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
