#include "Observer.h"




void Observer::Update()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-43-38--3b86ddc6:154b7f262c7:-8000:0000000000000892 begin
{
}
// section -64--88-43-38--3b86ddc6:154b7f262c7:-8000:0000000000000892 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
